version: '3.5'

networks:
  backend:
    driver: ${NETWORKS_DRIVER}

volumes:
  mysql:

services:
  server:
    build:
      context: ./server
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    ports:
      - "${SERVER_PORT}:80"
    privileged: true
    volumes:
      - ./server:/opt
    tty: true
    stdin_open: true
    networks:
      - backend

  database:
    build: 
      context: ./database
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TZ}
    volumes:
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
      - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - "${DATABASE_PORT}:3306"
    networks:
      - backend


